# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
# History plugin requires complete log
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version:
  au_push: true

  # Mail credentials - for error notifications
  mail_user:
    secure: 4Rz6zgVmEDLNpLtgajoG2iInK/azcGvdGR/gU8CDKPo= #https://ci.appveyor.com/tools/encrypt

  # Chocolatey API key - to push updated packages
  api_key:
    secure: Sdc8chxiPQ+U9JGWiT4ZSsJK4/LCkwTBaNDyPlCa85DUmNJEabZAE2e1jakRxLbd # https://ci.appveyor.com/tools/encrypt

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- choco --version
- ps: Install-Module AU
- ps: Install-Module Wormies-AU-Helpers
- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

# Uncomment the below line if you are using any of the functions from chocolatey-core.extension - https://chocolatey.org/packages/chocolatey-core.extension. Ensure you also have it listed in your package's dependencies
# - cinst chocolatey-core.extension
    
build_script:
- ps: |
    cd starship.portable
    ./update.ps1
- ps: |
    $pkg = (Get-Item starship.portable.*.nupkg).FullName
    $pkg
    choco apikey -k $env:api_key -s https://push.chocolatey.org/
    if (-not ($Env:APPVEYOR_REPO_COMMIT_MESSAGE -like 'nopush*')) {
      choco push $pkg --source https://push.chocolatey.org/
    }

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md
- path: au_temp.zip
- path: starship.portable/starship.portable.*.nupkg

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
